# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.storage_api import StorageApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self):
        self.api = StorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_storage_change_post(self):
        """Test case for storage_change_post

        Posts STORAGE_CHANGE payload  # noqa: E501
        """
        pass

    def test_storage_planets_user_name_get(self):
        """Test case for storage_planets_user_name_get

        Retrieves list of Planets where storage data exists for UserName  # noqa: E501
        """
        pass

    def test_storage_user_name_get(self):
        """Test case for storage_user_name_get

        Retrieves storage data  # noqa: E501
        """
        pass

    def test_storage_user_name_storage_description_get(self):
        """Test case for storage_user_name_storage_description_get

        Retrieves list of Planets where storage data exists for UserName  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
