# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.permission_shipment_tracking_api import PermissionShipmentTrackingApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestPermissionShipmentTrackingApi(unittest.TestCase):
    """PermissionShipmentTrackingApi unit test stubs"""

    def setUp(self):
        self.api = PermissionShipmentTrackingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contract_shipments_get(self):
        """Test case for contract_shipments_get

        Retrieves information on the location of your shipments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
