# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.cxos_api import CxosApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestCxosApi(unittest.TestCase):
    """CxosApi unit test stubs"""

    def setUp(self):
        self.api = CxosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cxos_added_post(self):
        """Test case for cxos_added_post

        Posts COMEX_TRADER_ORDER_ADDED data payload  # noqa: E501
        """
        pass

    def test_cxos_post(self):
        """Test case for cxos_post

        Posts COMEX_TRADER_ORDERS data payload  # noqa: E501
        """
        pass

    def test_cxos_removed_post(self):
        """Test case for cxos_removed_post

        Posts COMEX_TRADER_ORDER_REMOVED data payload  # noqa: E501
        """
        pass

    def test_cxos_updated_post(self):
        """Test case for cxos_updated_post

        Posts COMEX_TRADER_ORDER_UPDATED data payload  # noqa: E501
        """
        pass

    def test_cxos_user_name_get(self):
        """Test case for cxos_user_name_get

        Retrieves CXOS data for provided username.  See FIORest source for payload definition  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
