# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.csv_api import CsvApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestCsvApi(unittest.TestCase):
    """CsvApi unit test stubs"""

    def setUp(self):
        self.api = CsvApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_csv_bids_get(self):
        """Test case for csv_bids_get

        Price bid information  # noqa: E501
        """
        pass

    def test_csv_buildingcosts_get(self):
        """Test case for csv_buildingcosts_get

        Building cost information  # noqa: E501
        """
        pass

    def test_csv_buildingrecipes_get(self):
        """Test case for csv_buildingrecipes_get

        Building recipe information  # noqa: E501
        """
        pass

    def test_csv_buildings_get(self):
        """Test case for csv_buildings_get

        Building information  # noqa: E501
        """
        pass

    def test_csv_buildingworkforces_get(self):
        """Test case for csv_buildingworkforces_get

        Building workforce information  # noqa: E501
        """
        pass

    def test_csv_burnrate_get(self):
        """Test case for csv_burnrate_get

        A specified user's burnrate  # noqa: E501
        """
        pass

    def test_csv_cxos_get(self):
        """Test case for csv_cxos_get

        A specified user's CXOS trades  # noqa: E501
        """
        pass

    def test_csv_cxpc_ticker_get(self):
        """Test case for csv_cxpc_ticker_get

        CXPC data for a given ticker  # noqa: E501
        """
        pass

    def test_csv_infrastructure_allinfos_get(self):
        """Test case for csv_infrastructure_allinfos_get

        All infrastructure infos  # noqa: E501
        """
        pass

    def test_csv_infrastructure_allreports_get(self):
        """Test case for csv_infrastructure_allreports_get

        All infrastructure reports  # noqa: E501
        """
        pass

    def test_csv_infrastructure_infos_planet_get(self):
        """Test case for csv_infrastructure_infos_planet_get

        Infrastructure infos for a given planet  # noqa: E501
        """
        pass

    def test_csv_infrastructure_report_planet_get(self):
        """Test case for csv_infrastructure_report_planet_get

        Infrastructure report for a given planet  # noqa: E501
        """
        pass

    def test_csv_inventory_get(self):
        """Test case for csv_inventory_get

        A specified user's inventory  # noqa: E501
        """
        pass

    def test_csv_localmarket_buy_planet_get(self):
        """Test case for csv_localmarket_buy_planet_get

        All buy ads on a given planet's LM  # noqa: E501
        """
        pass

    def test_csv_localmarket_sell_planet_get(self):
        """Test case for csv_localmarket_sell_planet_get

        All sell ads on a given planet's LM  # noqa: E501
        """
        pass

    def test_csv_localmarket_ship_planet_get(self):
        """Test case for csv_localmarket_ship_planet_get

        All shipping ads on a given planet's LM  # noqa: E501
        """
        pass

    def test_csv_materials_get(self):
        """Test case for csv_materials_get

        Material information  # noqa: E501
        """
        pass

    def test_csv_orders_get(self):
        """Test case for csv_orders_get

        Price order information  # noqa: E501
        """
        pass

    def test_csv_planetdetail_get(self):
        """Test case for csv_planetdetail_get

        Detailed planet information  # noqa: E501
        """
        pass

    def test_csv_planetproductionfees_get(self):
        """Test case for csv_planetproductionfees_get

        Planet production fee information  # noqa: E501
        """
        pass

    def test_csv_planetresources_get(self):
        """Test case for csv_planetresources_get

        Planet resource information  # noqa: E501
        """
        pass

    def test_csv_planets_get(self):
        """Test case for csv_planets_get

        Planet information  # noqa: E501
        """
        pass

    def test_csv_prices_condensed_get(self):
        """Test case for csv_prices_condensed_get

        Price information (condensed horizontally)  # noqa: E501
        """
        pass

    def test_csv_prices_get(self):
        """Test case for csv_prices_get

        Full price information  # noqa: E501
        """
        pass

    def test_csv_recipeinputs_get(self):
        """Test case for csv_recipeinputs_get

        Recipe input information  # noqa: E501
        """
        pass

    def test_csv_recipeoutputs_get(self):
        """Test case for csv_recipeoutputs_get

        Recipe output information  # noqa: E501
        """
        pass

    def test_csv_sites_get(self):
        """Test case for csv_sites_get

        A specified user's sites  # noqa: E501
        """
        pass

    def test_csv_systemlinks_get(self):
        """Test case for csv_systemlinks_get

        System links  # noqa: E501
        """
        pass

    def test_csv_systemplanets_get(self):
        """Test case for csv_systemplanets_get

        System planet information  # noqa: E501
        """
        pass

    def test_csv_systems_get(self):
        """Test case for csv_systems_get

        System information  # noqa: E501
        """
        pass

    def test_csv_workforce_get(self):
        """Test case for csv_workforce_get

        A specified user's workforce information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
