# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.usersettings_api import UsersettingsApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestUsersettingsApi(unittest.TestCase):
    """UsersettingsApi unit test stubs"""

    def setUp(self):
        self.api = UsersettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_usersettings_burnrate_addexclusion_post(self):
        """Test case for usersettings_burnrate_addexclusion_post

        Adds a BurnRateExclusion  # noqa: E501
        """
        pass

    def test_usersettings_burnrate_deleteexclusion_post(self):
        """Test case for usersettings_burnrate_deleteexclusion_post

        Deletes a BurnRateExclusion  # noqa: E501
        """
        pass

    def test_usersettings_burnrate_redthreshold_post(self):
        """Test case for usersettings_burnrate_redthreshold_post

        Currently unused.  Will be used in the future  # noqa: E501
        """
        pass

    def test_usersettings_burnrate_user_name_get(self):
        """Test case for usersettings_burnrate_user_name_get

        Retrieves BurnRateSettings for the specified user  # noqa: E501
        """
        pass

    def test_usersettings_burnrate_user_name_planet_natural_id_get(self):
        """Test case for usersettings_burnrate_user_name_planet_natural_id_get

        Retrivies BurnRateSettings for the specified user on the specified planet  # noqa: E501
        """
        pass

    def test_usersettings_burnrate_yellowthreshold_post(self):
        """Test case for usersettings_burnrate_yellowthreshold_post

        Currently unused.  Will be used in the future  # noqa: E501
        """
        pass

    def test_usersettings_general_get(self):
        """Test case for usersettings_general_get

        Currently unused.  Will be used in the future  # noqa: E501
        """
        pass

    def test_usersettings_general_post(self):
        """Test case for usersettings_general_post

        Currently unused.  Will be used in the future  # noqa: E501
        """
        pass

    def test_usersettings_general_user_name_get(self):
        """Test case for usersettings_general_user_name_get

        Currently unused.  Will be used in the future  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
