# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.permission_production_api import PermissionProductionApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestPermissionProductionApi(unittest.TestCase):
    """PermissionProductionApi unit test stubs"""

    def setUp(self):
        self.api = PermissionProductionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_production_planets_user_name_get(self):
        """Test case for production_planets_user_name_get

        Retrieve all the planets where production lines are present for the provided UserName  # noqa: E501
        """
        pass

    def test_production_user_name_get(self):
        """Test case for production_user_name_get

        Retrieve all production lines for provided UserName  # noqa: E501
        """
        pass

    def test_production_user_name_planet_get(self):
        """Test case for production_user_name_planet_get

        Retrieve production line for the given UserName on the specified Planet  # noqa: E501
        """
        pass

    def test_rain_userplanetproduction_user_name_get(self):
        """Test case for rain_userplanetproduction_user_name_get

        Retrieves planet production for the given UserName  # noqa: E501
        """
        pass

    def test_rain_userplanetproductioninput_user_name_get(self):
        """Test case for rain_userplanetproductioninput_user_name_get

        Retrieves planet production inputs for the given UserName  # noqa: E501
        """
        pass

    def test_rain_userplanetproductionoutput_user_name_get(self):
        """Test case for rain_userplanetproductionoutput_user_name_get

        Retrieves planet production outputs for the given UserName  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
