# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.permission_building_api import PermissionBuildingApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestPermissionBuildingApi(unittest.TestCase):
    """PermissionBuildingApi unit test stubs"""

    def setUp(self):
        self.api = PermissionBuildingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rain_userplanetbuildingreclaimables_user_name_get(self):
        """Test case for rain_userplanetbuildingreclaimables_user_name_get

        Retrieves planet building reclaimables for the given UserName  # noqa: E501
        """
        pass

    def test_rain_userplanetbuildings_user_name_get(self):
        """Test case for rain_userplanetbuildings_user_name_get

        Retrieves planet buildings for the given UserName  # noqa: E501
        """
        pass

    def test_sites_planets_user_name_get(self):
        """Test case for sites_planets_user_name_get

        Retrieves list of planets user has site data for  # noqa: E501
        """
        pass

    def test_sites_user_name_get(self):
        """Test case for sites_user_name_get

        Retrieves site data  # noqa: E501
        """
        pass

    def test_sites_user_name_planet_get(self):
        """Test case for sites_user_name_planet_get

        Retrieves list of planets user has site data for  # noqa: E501
        """
        pass

    def test_sites_warehouses_user_name_get(self):
        """Test case for sites_warehouses_user_name_get

        Retrieves all warehouse sites the user has  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
