# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.localmarket_api import LocalmarketApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestLocalmarketApi(unittest.TestCase):
    """LocalmarketApi unit test stubs"""

    def setUp(self):
        self.api = LocalmarketApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_localmarket_company_company_get(self):
        """Test case for localmarket_company_company_get

        Retrieves all ads found by specified Company  # noqa: E501
        """
        pass

    def test_localmarket_local_market_id_get(self):
        """Test case for localmarket_local_market_id_get

        Retrieves LocalMarket data for the provided LocalMarketId  # noqa: E501
        """
        pass

    def test_localmarket_planet_planet_get(self):
        """Test case for localmarket_planet_planet_get

        Retrieves LocalMarket data for provided Planet  # noqa: E501
        """
        pass

    def test_localmarket_planet_planet_type_get(self):
        """Test case for localmarket_planet_planet_type_get

        Retrieves LocalMarket data for provided Planet and specified type  # noqa: E501
        """
        pass

    def test_localmarket_post(self):
        """Test case for localmarket_post

        Posts LOCAL_MARKET_DATA_DATA data payload  # noqa: E501
        """
        pass

    def test_localmarket_search_post(self):
        """Test case for localmarket_search_post

        Searches all local markets for a given material  # noqa: E501
        """
        pass

    def test_localmarket_shipping_destination_destination_planet_get(self):
        """Test case for localmarket_shipping_destination_destination_planet_get

        Retrieves shipping LocalMarket data for the provided Planet where the drop-off location is DestinationPlanet  # noqa: E501
        """
        pass

    def test_localmarket_shipping_source_source_planet_get(self):
        """Test case for localmarket_shipping_source_source_planet_get

        Retrieves shipping LocalMarket data for the provided Planet where the pick-up location is SourcePlanet  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
