# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.ship_api import ShipApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestShipApi(unittest.TestCase):
    """ShipApi unit test stubs"""

    def setUp(self):
        self.api = ShipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ship_flights_post(self):
        """Test case for ship_flights_post

        Posts SHIP_FLIGHT_FLIGHTS payload  # noqa: E501
        """
        pass

    def test_ship_flights_user_name_get(self):
        """Test case for ship_flights_user_name_get

        Retrieves ship flight data  # noqa: E501
        """
        pass

    def test_ship_ships_fuel_user_name_get(self):
        """Test case for ship_ships_fuel_user_name_get

        Retrieves ship fuel store data  # noqa: E501
        """
        pass

    def test_ship_ships_post(self):
        """Test case for ship_ships_post

        Posts SHIP_SHIPS payload  # noqa: E501
        """
        pass

    def test_ship_ships_user_name_get(self):
        """Test case for ship_ships_user_name_get

        Retrieves ship data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
