# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.permission_workforce_api import PermissionWorkforceApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestPermissionWorkforceApi(unittest.TestCase):
    """PermissionWorkforceApi unit test stubs"""

    def setUp(self):
        self.api = PermissionWorkforceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rain_userplanetworkforce_user_name_get(self):
        """Test case for rain_userplanetworkforce_user_name_get

        Retrieves planet production workforces for the given UserName  # noqa: E501
        """
        pass

    def test_usersettings_burnrate_user_name_get(self):
        """Test case for usersettings_burnrate_user_name_get

        Retrieves BurnRateSettings for the specified user  # noqa: E501
        """
        pass

    def test_usersettings_burnrate_user_name_planet_natural_id_get(self):
        """Test case for usersettings_burnrate_user_name_planet_natural_id_get

        Retrivies BurnRateSettings for the specified user on the specified planet  # noqa: E501
        """
        pass

    def test_workforce_planets_user_name_get(self):
        """Test case for workforce_planets_user_name_get

        Retrieves list of planets where the specified user has Workforce data  # noqa: E501
        """
        pass

    def test_workforce_user_name_get(self):
        """Test case for workforce_user_name_get

        Retrieves workforce data for the specified user  # noqa: E501
        """
        pass

    def test_workforce_user_name_planet_get(self):
        """Test case for workforce_user_name_planet_get

        Retrieves workforce data for the specified usernaem and planet  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
