# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.auth_api import AuthApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_addpermission_post(self):
        """Test case for auth_addpermission_post

        Add a permission allowance  # noqa: E501
        """
        pass

    def test_auth_changepassword_post(self):
        """Test case for auth_changepassword_post

        Changes the user's password  # noqa: E501
        """
        pass

    def test_auth_createapikey_post(self):
        """Test case for auth_createapikey_post

        Creates an API key  # noqa: E501
        """
        pass

    def test_auth_creategroup_post(self):
        """Test case for auth_creategroup_post

        Creates a group or modifies an existing group if GroupId is specified  # noqa: E501
        """
        pass

    def test_auth_deletegroup_group_id_post(self):
        """Test case for auth_deletegroup_group_id_post

        Deletes a group you own by id  # noqa: E501
        """
        pass

    def test_auth_deletepermission_user_name_post(self):
        """Test case for auth_deletepermission_user_name_post

        Delete a permission allowance  # noqa: E501
        """
        pass

    def test_auth_get(self):
        """Test case for auth_get

        Determines if the user is authenticated  # noqa: E501
        """
        pass

    def test_auth_group_group_id_get(self):
        """Test case for auth_group_group_id_get

        Retrieves group by GroupId  # noqa: E501
        """
        pass

    def test_auth_groups_get(self):
        """Test case for auth_groups_get

        Retrieves all groups owned by the current user  # noqa: E501
        """
        pass

    def test_auth_listapikeys_post(self):
        """Test case for auth_listapikeys_post

        Lists all API keys  # noqa: E501
        """
        pass

    def test_auth_login_post(self):
        """Test case for auth_login_post

        Login to FIO  # noqa: E501
        """
        pass

    def test_auth_permissions_get(self):
        """Test case for auth_permissions_get

        Retrieves all permission allowances  # noqa: E501
        """
        pass

    def test_auth_refreshauthtoken_post(self):
        """Test case for auth_refreshauthtoken_post

        Refreshes the user's auth token  # noqa: E501
        """
        pass

    def test_auth_revokeapikey_post(self):
        """Test case for auth_revokeapikey_post

        Revokes an API key  # noqa: E501
        """
        pass

    def test_auth_visibility_get(self):
        """Test case for auth_visibility_get

        Retrieves all allowances given to the user  # noqa: E501
        """
        pass

    def test_auth_visibility_permission_type_get(self):
        """Test case for auth_visibility_permission_type_get

        Retrieves all users where we have the permissionType specified given to us  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
