# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.systemstars_api import SystemstarsApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestSystemstarsApi(unittest.TestCase):
    """SystemstarsApi unit test stubs"""

    def setUp(self):
        self.api = SystemstarsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_systemstars_get(self):
        """Test case for systemstars_get

        Retrieves system star data  # noqa: E501
        """
        pass

    def test_systemstars_jumpcount_source_destination_get(self):
        """Test case for systemstars_jumpcount_source_destination_get

        Retrieves jump count from source to destination specified  # noqa: E501
        """
        pass

    def test_systemstars_jumproute_source_destination_get(self):
        """Test case for systemstars_jumproute_source_destination_get

        Retrieves jump route from source to destination specified  # noqa: E501
        """
        pass

    def test_systemstars_post(self):
        """Test case for systemstars_post

        Posts SYSTEM_STARS_DATA payload  # noqa: E501
        """
        pass

    def test_systemstars_star_post(self):
        """Test case for systemstars_star_post

        Posts SYSTEM_STAR data  # noqa: E501
        """
        pass

    def test_systemstars_star_star_get(self):
        """Test case for systemstars_star_star_get

        Retrieves SYSTEM_STAR data provided a Star definition  # noqa: E501
        """
        pass

    def test_systemstars_worldsectors_get(self):
        """Test case for systemstars_worldsectors_get

        Retrieves world sector data  # noqa: E501
        """
        pass

    def test_systemstars_worldsectors_post(self):
        """Test case for systemstars_worldsectors_post

        Posts WORLD_SECTORS payload  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
