# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.company_api import CompanyApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestCompanyApi(unittest.TestCase):
    """CompanyApi unit test stubs"""

    def setUp(self):
        self.api = CompanyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_company_code_company_code_get(self):
        """Test case for company_code_company_code_get

        Retrieves company data by CompanyCode  # noqa: E501
        """
        pass

    def test_company_data_post(self):
        """Test case for company_data_post

        Posts COMPANY_DATA_DATA payload.  For payload, see FIORest source  # noqa: E501
        """
        pass

    def test_company_name_company_name_get(self):
        """Test case for company_name_company_name_get

        Retrieves company data by CompanyName  # noqa: E501
        """
        pass

    def test_company_post(self):
        """Test case for company_post

        Posts COMPANY_DATA payload.  For payload, see FIORest source  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
