# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.planet_api import PlanetApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestPlanetApi(unittest.TestCase):
    """PlanetApi unit test stubs"""

    def setUp(self):
        self.api = PlanetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_planet_allplanets_full_get(self):
        """Test case for planet_allplanets_full_get

        Retrieves all planet data for all planets  # noqa: E501
        """
        pass

    def test_planet_allplanets_get(self):
        """Test case for planet_allplanets_get

        Retrieves a list of all planets (minimal payload)  # noqa: E501
        """
        pass

    def test_planet_cogc_post(self):
        """Test case for planet_cogc_post

        Posts PLANET_COGC_DATA payload  # noqa: E501
        """
        pass

    def test_planet_planet_get(self):
        """Test case for planet_planet_get

        Retrieves planet payload.  See FIORest for payload definition  # noqa: E501
        """
        pass

    def test_planet_post(self):
        """Test case for planet_post

        Posts PLANET_DATA_DATA payload  # noqa: E501
        """
        pass

    def test_planet_search_post(self):
        """Test case for planet_search_post

        Searches for a planet given the parameters in the payload  # noqa: E501
        """
        pass

    def test_planet_sites_planet_get(self):
        """Test case for planet_sites_planet_get

        Retrieves the planet sites payload.  See FIORest for payload definition  # noqa: E501
        """
        pass

    def test_planet_sites_post(self):
        """Test case for planet_sites_post

        Posts PLANET_SITES payload  # noqa: E501
        """
        pass

    def test_planet_sitescount_planet_get(self):
        """Test case for planet_sitescount_planet_get

        Retrieves the number of planet sites for the provided Planet  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
