# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.exchange_api import ExchangeApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestExchangeApi(unittest.TestCase):
    """ExchangeApi unit test stubs"""

    def setUp(self):
        self.api = ExchangeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_exchange_all_get(self):
        """Test case for exchange_all_get

        Retrieves summarized information of all exchange data  # noqa: E501
        """
        pass

    def test_exchange_cxpc_exchange_ticker_get(self):
        """Test case for exchange_cxpc_exchange_ticker_get

        Retrieves exchange price chart data for the given ticker  # noqa: E501
        """
        pass

    def test_exchange_cxpc_exchange_ticker_time_stamp_get(self):
        """Test case for exchange_cxpc_exchange_ticker_time_stamp_get

        Retrieves exchange price chart data for the given ticker  # noqa: E501
        """
        pass

    def test_exchange_exchange_ticker_get(self):
        """Test case for exchange_exchange_ticker_get

        Retrieves Exchange data for the provided ExchangeTicker  # noqa: E501
        """
        pass

    def test_exchange_full_get(self):
        """Test case for exchange_full_get

        Retrieves all the exchange data, including order info  # noqa: E501
        """
        pass

    def test_exchange_orders_company_code_exchange_code_get(self):
        """Test case for exchange_orders_company_code_exchange_code_get

        Retrieves a provided company code's orders on all exchanges  # noqa: E501
        """
        pass

    def test_exchange_orders_company_code_get(self):
        """Test case for exchange_orders_company_code_get

        Retrieves a provided company code's orders on all exchanges  # noqa: E501
        """
        pass

    def test_exchange_post(self):
        """Test case for exchange_post

        Posts COMEX_BROKER_DATA data payload  # noqa: E501
        """
        pass

    def test_exchange_station_get(self):
        """Test case for exchange_station_get

        Retrieves all exchange station data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
