# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fio_sdk
from fio_sdk.api.chat_api import ChatApi  # noqa: E501
from fio_sdk.rest import ApiException


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self):
        self.api = ChatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chat_data_post(self):
        """Test case for chat_data_post

        Posts the CHANNEL_DATA payload to the server.  For payload, see FIORest source  # noqa: E501
        """
        pass

    def test_chat_display_channel_description_get(self):
        """Test case for chat_display_channel_description_get

        Retrieves the last 300 messages of the provided ChannelDescription  # noqa: E501
        """
        pass

    def test_chat_display_pretty_channel_description_get(self):
        """Test case for chat_display_pretty_channel_description_get

        Retrieves the last 300 messages of the provided ChannelDescription in a 'pretty' (textual) format  # noqa: E501
        """
        pass

    def test_chat_list_get(self):
        """Test case for chat_list_get

        Retrieves a list of searchable channel names and their corresponding ChannelIds  # noqa: E501
        """
        pass

    def test_chat_message_added_post(self):
        """Test case for chat_message_added_post

        Posts the CHANNEL_MESSAGE_ADDED payload to the server.  For payload, see FIORest source  # noqa: E501
        """
        pass

    def test_chat_message_deleted_post(self):
        """Test case for chat_message_deleted_post

        Posts the CHANNEL_MESSAGE_DELETED payload to the server.  For payload, see FIORest source  # noqa: E501
        """
        pass

    def test_chat_message_list_post(self):
        """Test case for chat_message_list_post

        Posts the CHANNEL_MESSAGE_LIST payload to the server.  For payload, see FIORest source  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
