# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthLoginResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auth_token': 'str',
        'expiry': 'str',
        'is_administrator': 'bool'
    }

    attribute_map = {
        'auth_token': 'AuthToken',
        'expiry': 'Expiry',
        'is_administrator': 'IsAdministrator'
    }

    def __init__(self, auth_token=None, expiry=None, is_administrator=None):  # noqa: E501
        """AuthLoginResponse - a model defined in Swagger"""  # noqa: E501
        self._auth_token = None
        self._expiry = None
        self._is_administrator = None
        self.discriminator = None
        if auth_token is not None:
            self.auth_token = auth_token
        if expiry is not None:
            self.expiry = expiry
        if is_administrator is not None:
            self.is_administrator = is_administrator

    @property
    def auth_token(self):
        """Gets the auth_token of this AuthLoginResponse.  # noqa: E501


        :return: The auth_token of this AuthLoginResponse.  # noqa: E501
        :rtype: str
        """
        return self._auth_token

    @auth_token.setter
    def auth_token(self, auth_token):
        """Sets the auth_token of this AuthLoginResponse.


        :param auth_token: The auth_token of this AuthLoginResponse.  # noqa: E501
        :type: str
        """

        self._auth_token = auth_token

    @property
    def expiry(self):
        """Gets the expiry of this AuthLoginResponse.  # noqa: E501


        :return: The expiry of this AuthLoginResponse.  # noqa: E501
        :rtype: str
        """
        return self._expiry

    @expiry.setter
    def expiry(self, expiry):
        """Sets the expiry of this AuthLoginResponse.


        :param expiry: The expiry of this AuthLoginResponse.  # noqa: E501
        :type: str
        """

        self._expiry = expiry

    @property
    def is_administrator(self):
        """Gets the is_administrator of this AuthLoginResponse.  # noqa: E501


        :return: The is_administrator of this AuthLoginResponse.  # noqa: E501
        :rtype: bool
        """
        return self._is_administrator

    @is_administrator.setter
    def is_administrator(self, is_administrator):
        """Sets the is_administrator of this AuthLoginResponse.


        :param is_administrator: The is_administrator of this AuthLoginResponse.  # noqa: E501
        :type: bool
        """

        self._is_administrator = is_administrator

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthLoginResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthLoginResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
