# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthCreateApiKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_name': 'str',
        'password': 'str',
        'allow_writes': 'bool',
        'application': 'str'
    }

    attribute_map = {
        'user_name': 'UserName',
        'password': 'Password',
        'allow_writes': 'AllowWrites',
        'application': 'Application'
    }

    def __init__(self, user_name=None, password=None, allow_writes=None, application=None):  # noqa: E501
        """AuthCreateApiKey - a model defined in Swagger"""  # noqa: E501
        self._user_name = None
        self._password = None
        self._allow_writes = None
        self._application = None
        self.discriminator = None
        if user_name is not None:
            self.user_name = user_name
        if password is not None:
            self.password = password
        if allow_writes is not None:
            self.allow_writes = allow_writes
        if application is not None:
            self.application = application

    @property
    def user_name(self):
        """Gets the user_name of this AuthCreateApiKey.  # noqa: E501


        :return: The user_name of this AuthCreateApiKey.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this AuthCreateApiKey.


        :param user_name: The user_name of this AuthCreateApiKey.  # noqa: E501
        :type: str
        """

        self._user_name = user_name

    @property
    def password(self):
        """Gets the password of this AuthCreateApiKey.  # noqa: E501


        :return: The password of this AuthCreateApiKey.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AuthCreateApiKey.


        :param password: The password of this AuthCreateApiKey.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def allow_writes(self):
        """Gets the allow_writes of this AuthCreateApiKey.  # noqa: E501


        :return: The allow_writes of this AuthCreateApiKey.  # noqa: E501
        :rtype: bool
        """
        return self._allow_writes

    @allow_writes.setter
    def allow_writes(self, allow_writes):
        """Sets the allow_writes of this AuthCreateApiKey.


        :param allow_writes: The allow_writes of this AuthCreateApiKey.  # noqa: E501
        :type: bool
        """

        self._allow_writes = allow_writes

    @property
    def application(self):
        """Gets the application of this AuthCreateApiKey.  # noqa: E501


        :return: The application of this AuthCreateApiKey.  # noqa: E501
        :rtype: str
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this AuthCreateApiKey.


        :param application: The application of this AuthCreateApiKey.  # noqa: E501
        :type: str
        """

        self._application = application

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthCreateApiKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthCreateApiKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
