# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LocalMarketSearch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'search_buys': 'bool',
        'search_sells': 'bool',
        'ticker': 'str',
        'cost_threshold': 'float',
        'source_location': 'str'
    }

    attribute_map = {
        'search_buys': 'SearchBuys',
        'search_sells': 'SearchSells',
        'ticker': 'Ticker',
        'cost_threshold': 'CostThreshold',
        'source_location': 'SourceLocation'
    }

    def __init__(self, search_buys=None, search_sells=None, ticker=None, cost_threshold=None, source_location=None):  # noqa: E501
        """LocalMarketSearch - a model defined in Swagger"""  # noqa: E501
        self._search_buys = None
        self._search_sells = None
        self._ticker = None
        self._cost_threshold = None
        self._source_location = None
        self.discriminator = None
        if search_buys is not None:
            self.search_buys = search_buys
        if search_sells is not None:
            self.search_sells = search_sells
        if ticker is not None:
            self.ticker = ticker
        if cost_threshold is not None:
            self.cost_threshold = cost_threshold
        if source_location is not None:
            self.source_location = source_location

    @property
    def search_buys(self):
        """Gets the search_buys of this LocalMarketSearch.  # noqa: E501


        :return: The search_buys of this LocalMarketSearch.  # noqa: E501
        :rtype: bool
        """
        return self._search_buys

    @search_buys.setter
    def search_buys(self, search_buys):
        """Sets the search_buys of this LocalMarketSearch.


        :param search_buys: The search_buys of this LocalMarketSearch.  # noqa: E501
        :type: bool
        """

        self._search_buys = search_buys

    @property
    def search_sells(self):
        """Gets the search_sells of this LocalMarketSearch.  # noqa: E501


        :return: The search_sells of this LocalMarketSearch.  # noqa: E501
        :rtype: bool
        """
        return self._search_sells

    @search_sells.setter
    def search_sells(self, search_sells):
        """Sets the search_sells of this LocalMarketSearch.


        :param search_sells: The search_sells of this LocalMarketSearch.  # noqa: E501
        :type: bool
        """

        self._search_sells = search_sells

    @property
    def ticker(self):
        """Gets the ticker of this LocalMarketSearch.  # noqa: E501


        :return: The ticker of this LocalMarketSearch.  # noqa: E501
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker):
        """Sets the ticker of this LocalMarketSearch.


        :param ticker: The ticker of this LocalMarketSearch.  # noqa: E501
        :type: str
        """

        self._ticker = ticker

    @property
    def cost_threshold(self):
        """Gets the cost_threshold of this LocalMarketSearch.  # noqa: E501


        :return: The cost_threshold of this LocalMarketSearch.  # noqa: E501
        :rtype: float
        """
        return self._cost_threshold

    @cost_threshold.setter
    def cost_threshold(self, cost_threshold):
        """Sets the cost_threshold of this LocalMarketSearch.


        :param cost_threshold: The cost_threshold of this LocalMarketSearch.  # noqa: E501
        :type: float
        """

        self._cost_threshold = cost_threshold

    @property
    def source_location(self):
        """Gets the source_location of this LocalMarketSearch.  # noqa: E501


        :return: The source_location of this LocalMarketSearch.  # noqa: E501
        :rtype: str
        """
        return self._source_location

    @source_location.setter
    def source_location(self, source_location):
        """Sets the source_location of this LocalMarketSearch.


        :param source_location: The source_location of this LocalMarketSearch.  # noqa: E501
        :type: str
        """

        self._source_location = source_location

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LocalMarketSearch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LocalMarketSearch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
