# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlanetSearchRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'materials': 'list[str]',
        'include_rocky': 'bool',
        'include_gaseous': 'bool',
        'include_low_gravity': 'bool',
        'include_high_gravity': 'bool',
        'include_low_pressure': 'bool',
        'include_high_pressure': 'bool',
        'include_low_temperature': 'bool',
        'include_high_temperature': 'bool',
        'must_be_fertile': 'bool',
        'must_have_local_market': 'bool',
        'must_have_chamber_of_commerce': 'bool',
        'must_have_warehouse': 'bool',
        'must_have_administration_center': 'bool',
        'must_have_shipyard': 'bool',
        'distance_checks': 'list[str]'
    }

    attribute_map = {
        'materials': 'Materials',
        'include_rocky': 'IncludeRocky',
        'include_gaseous': 'IncludeGaseous',
        'include_low_gravity': 'IncludeLowGravity',
        'include_high_gravity': 'IncludeHighGravity',
        'include_low_pressure': 'IncludeLowPressure',
        'include_high_pressure': 'IncludeHighPressure',
        'include_low_temperature': 'IncludeLowTemperature',
        'include_high_temperature': 'IncludeHighTemperature',
        'must_be_fertile': 'MustBeFertile',
        'must_have_local_market': 'MustHaveLocalMarket',
        'must_have_chamber_of_commerce': 'MustHaveChamberOfCommerce',
        'must_have_warehouse': 'MustHaveWarehouse',
        'must_have_administration_center': 'MustHaveAdministrationCenter',
        'must_have_shipyard': 'MustHaveShipyard',
        'distance_checks': 'DistanceChecks'
    }

    def __init__(self, materials=None, include_rocky=None, include_gaseous=None, include_low_gravity=None, include_high_gravity=None, include_low_pressure=None, include_high_pressure=None, include_low_temperature=None, include_high_temperature=None, must_be_fertile=None, must_have_local_market=None, must_have_chamber_of_commerce=None, must_have_warehouse=None, must_have_administration_center=None, must_have_shipyard=None, distance_checks=None):  # noqa: E501
        """PlanetSearchRequest - a model defined in Swagger"""  # noqa: E501
        self._materials = None
        self._include_rocky = None
        self._include_gaseous = None
        self._include_low_gravity = None
        self._include_high_gravity = None
        self._include_low_pressure = None
        self._include_high_pressure = None
        self._include_low_temperature = None
        self._include_high_temperature = None
        self._must_be_fertile = None
        self._must_have_local_market = None
        self._must_have_chamber_of_commerce = None
        self._must_have_warehouse = None
        self._must_have_administration_center = None
        self._must_have_shipyard = None
        self._distance_checks = None
        self.discriminator = None
        if materials is not None:
            self.materials = materials
        if include_rocky is not None:
            self.include_rocky = include_rocky
        if include_gaseous is not None:
            self.include_gaseous = include_gaseous
        if include_low_gravity is not None:
            self.include_low_gravity = include_low_gravity
        if include_high_gravity is not None:
            self.include_high_gravity = include_high_gravity
        if include_low_pressure is not None:
            self.include_low_pressure = include_low_pressure
        if include_high_pressure is not None:
            self.include_high_pressure = include_high_pressure
        if include_low_temperature is not None:
            self.include_low_temperature = include_low_temperature
        if include_high_temperature is not None:
            self.include_high_temperature = include_high_temperature
        if must_be_fertile is not None:
            self.must_be_fertile = must_be_fertile
        if must_have_local_market is not None:
            self.must_have_local_market = must_have_local_market
        if must_have_chamber_of_commerce is not None:
            self.must_have_chamber_of_commerce = must_have_chamber_of_commerce
        if must_have_warehouse is not None:
            self.must_have_warehouse = must_have_warehouse
        if must_have_administration_center is not None:
            self.must_have_administration_center = must_have_administration_center
        if must_have_shipyard is not None:
            self.must_have_shipyard = must_have_shipyard
        if distance_checks is not None:
            self.distance_checks = distance_checks

    @property
    def materials(self):
        """Gets the materials of this PlanetSearchRequest.  # noqa: E501


        :return: The materials of this PlanetSearchRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._materials

    @materials.setter
    def materials(self, materials):
        """Sets the materials of this PlanetSearchRequest.


        :param materials: The materials of this PlanetSearchRequest.  # noqa: E501
        :type: list[str]
        """

        self._materials = materials

    @property
    def include_rocky(self):
        """Gets the include_rocky of this PlanetSearchRequest.  # noqa: E501


        :return: The include_rocky of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_rocky

    @include_rocky.setter
    def include_rocky(self, include_rocky):
        """Sets the include_rocky of this PlanetSearchRequest.


        :param include_rocky: The include_rocky of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._include_rocky = include_rocky

    @property
    def include_gaseous(self):
        """Gets the include_gaseous of this PlanetSearchRequest.  # noqa: E501


        :return: The include_gaseous of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_gaseous

    @include_gaseous.setter
    def include_gaseous(self, include_gaseous):
        """Sets the include_gaseous of this PlanetSearchRequest.


        :param include_gaseous: The include_gaseous of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._include_gaseous = include_gaseous

    @property
    def include_low_gravity(self):
        """Gets the include_low_gravity of this PlanetSearchRequest.  # noqa: E501


        :return: The include_low_gravity of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_low_gravity

    @include_low_gravity.setter
    def include_low_gravity(self, include_low_gravity):
        """Sets the include_low_gravity of this PlanetSearchRequest.


        :param include_low_gravity: The include_low_gravity of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._include_low_gravity = include_low_gravity

    @property
    def include_high_gravity(self):
        """Gets the include_high_gravity of this PlanetSearchRequest.  # noqa: E501


        :return: The include_high_gravity of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_high_gravity

    @include_high_gravity.setter
    def include_high_gravity(self, include_high_gravity):
        """Sets the include_high_gravity of this PlanetSearchRequest.


        :param include_high_gravity: The include_high_gravity of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._include_high_gravity = include_high_gravity

    @property
    def include_low_pressure(self):
        """Gets the include_low_pressure of this PlanetSearchRequest.  # noqa: E501


        :return: The include_low_pressure of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_low_pressure

    @include_low_pressure.setter
    def include_low_pressure(self, include_low_pressure):
        """Sets the include_low_pressure of this PlanetSearchRequest.


        :param include_low_pressure: The include_low_pressure of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._include_low_pressure = include_low_pressure

    @property
    def include_high_pressure(self):
        """Gets the include_high_pressure of this PlanetSearchRequest.  # noqa: E501


        :return: The include_high_pressure of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_high_pressure

    @include_high_pressure.setter
    def include_high_pressure(self, include_high_pressure):
        """Sets the include_high_pressure of this PlanetSearchRequest.


        :param include_high_pressure: The include_high_pressure of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._include_high_pressure = include_high_pressure

    @property
    def include_low_temperature(self):
        """Gets the include_low_temperature of this PlanetSearchRequest.  # noqa: E501


        :return: The include_low_temperature of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_low_temperature

    @include_low_temperature.setter
    def include_low_temperature(self, include_low_temperature):
        """Sets the include_low_temperature of this PlanetSearchRequest.


        :param include_low_temperature: The include_low_temperature of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._include_low_temperature = include_low_temperature

    @property
    def include_high_temperature(self):
        """Gets the include_high_temperature of this PlanetSearchRequest.  # noqa: E501


        :return: The include_high_temperature of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_high_temperature

    @include_high_temperature.setter
    def include_high_temperature(self, include_high_temperature):
        """Sets the include_high_temperature of this PlanetSearchRequest.


        :param include_high_temperature: The include_high_temperature of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._include_high_temperature = include_high_temperature

    @property
    def must_be_fertile(self):
        """Gets the must_be_fertile of this PlanetSearchRequest.  # noqa: E501


        :return: The must_be_fertile of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._must_be_fertile

    @must_be_fertile.setter
    def must_be_fertile(self, must_be_fertile):
        """Sets the must_be_fertile of this PlanetSearchRequest.


        :param must_be_fertile: The must_be_fertile of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._must_be_fertile = must_be_fertile

    @property
    def must_have_local_market(self):
        """Gets the must_have_local_market of this PlanetSearchRequest.  # noqa: E501


        :return: The must_have_local_market of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._must_have_local_market

    @must_have_local_market.setter
    def must_have_local_market(self, must_have_local_market):
        """Sets the must_have_local_market of this PlanetSearchRequest.


        :param must_have_local_market: The must_have_local_market of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._must_have_local_market = must_have_local_market

    @property
    def must_have_chamber_of_commerce(self):
        """Gets the must_have_chamber_of_commerce of this PlanetSearchRequest.  # noqa: E501


        :return: The must_have_chamber_of_commerce of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._must_have_chamber_of_commerce

    @must_have_chamber_of_commerce.setter
    def must_have_chamber_of_commerce(self, must_have_chamber_of_commerce):
        """Sets the must_have_chamber_of_commerce of this PlanetSearchRequest.


        :param must_have_chamber_of_commerce: The must_have_chamber_of_commerce of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._must_have_chamber_of_commerce = must_have_chamber_of_commerce

    @property
    def must_have_warehouse(self):
        """Gets the must_have_warehouse of this PlanetSearchRequest.  # noqa: E501


        :return: The must_have_warehouse of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._must_have_warehouse

    @must_have_warehouse.setter
    def must_have_warehouse(self, must_have_warehouse):
        """Sets the must_have_warehouse of this PlanetSearchRequest.


        :param must_have_warehouse: The must_have_warehouse of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._must_have_warehouse = must_have_warehouse

    @property
    def must_have_administration_center(self):
        """Gets the must_have_administration_center of this PlanetSearchRequest.  # noqa: E501


        :return: The must_have_administration_center of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._must_have_administration_center

    @must_have_administration_center.setter
    def must_have_administration_center(self, must_have_administration_center):
        """Sets the must_have_administration_center of this PlanetSearchRequest.


        :param must_have_administration_center: The must_have_administration_center of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._must_have_administration_center = must_have_administration_center

    @property
    def must_have_shipyard(self):
        """Gets the must_have_shipyard of this PlanetSearchRequest.  # noqa: E501


        :return: The must_have_shipyard of this PlanetSearchRequest.  # noqa: E501
        :rtype: bool
        """
        return self._must_have_shipyard

    @must_have_shipyard.setter
    def must_have_shipyard(self, must_have_shipyard):
        """Sets the must_have_shipyard of this PlanetSearchRequest.


        :param must_have_shipyard: The must_have_shipyard of this PlanetSearchRequest.  # noqa: E501
        :type: bool
        """

        self._must_have_shipyard = must_have_shipyard

    @property
    def distance_checks(self):
        """Gets the distance_checks of this PlanetSearchRequest.  # noqa: E501


        :return: The distance_checks of this PlanetSearchRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._distance_checks

    @distance_checks.setter
    def distance_checks(self, distance_checks):
        """Sets the distance_checks of this PlanetSearchRequest.


        :param distance_checks: The distance_checks of this PlanetSearchRequest.  # noqa: E501
        :type: list[str]
        """

        self._distance_checks = distance_checks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlanetSearchRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlanetSearchRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
