# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RainBuilding(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ticker': 'str',
        'name': 'str',
        'area': 'int',
        'expertise': 'str'
    }

    attribute_map = {
        'ticker': 'Ticker',
        'name': 'Name',
        'area': 'Area',
        'expertise': 'Expertise'
    }

    def __init__(self, ticker=None, name=None, area=None, expertise=None):  # noqa: E501
        """RainBuilding - a model defined in Swagger"""  # noqa: E501
        self._ticker = None
        self._name = None
        self._area = None
        self._expertise = None
        self.discriminator = None
        if ticker is not None:
            self.ticker = ticker
        if name is not None:
            self.name = name
        if area is not None:
            self.area = area
        if expertise is not None:
            self.expertise = expertise

    @property
    def ticker(self):
        """Gets the ticker of this RainBuilding.  # noqa: E501


        :return: The ticker of this RainBuilding.  # noqa: E501
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker):
        """Sets the ticker of this RainBuilding.


        :param ticker: The ticker of this RainBuilding.  # noqa: E501
        :type: str
        """

        self._ticker = ticker

    @property
    def name(self):
        """Gets the name of this RainBuilding.  # noqa: E501


        :return: The name of this RainBuilding.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RainBuilding.


        :param name: The name of this RainBuilding.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def area(self):
        """Gets the area of this RainBuilding.  # noqa: E501


        :return: The area of this RainBuilding.  # noqa: E501
        :rtype: int
        """
        return self._area

    @area.setter
    def area(self, area):
        """Sets the area of this RainBuilding.


        :param area: The area of this RainBuilding.  # noqa: E501
        :type: int
        """

        self._area = area

    @property
    def expertise(self):
        """Gets the expertise of this RainBuilding.  # noqa: E501


        :return: The expertise of this RainBuilding.  # noqa: E501
        :rtype: str
        """
        return self._expertise

    @expertise.setter
    def expertise(self, expertise):
        """Sets the expertise of this RainBuilding.


        :param expertise: The expertise of this RainBuilding.  # noqa: E501
        :type: str
        """

        self._expertise = expertise

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RainBuilding, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RainBuilding):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
