# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RainPrices(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ticker': 'str',
        'mm_buy': 'float',
        'mm_sell': 'float',
        'ci1_average': 'float',
        'ci1_ask_amt': 'int',
        'ci1_ask_price': 'float',
        'ci1_ask_avail': 'int',
        'ci1_bid_amt': 'int',
        'ci1_bid_price': 'float',
        'ci1_bid_avail': 'int',
        'ni1_average': 'float',
        'ni1_ask_amt': 'int',
        'ni1_ask_price': 'float',
        'ni1_ask_avail': 'int',
        'ni1_bid_amt': 'int',
        'ni1_bid_price': 'float',
        'ni1_bid_avail': 'int',
        'ic1_average': 'float',
        'ic1_ask_amt': 'int',
        'ic1_ask_price': 'float',
        'ic1_ask_avail': 'int',
        'ic1_bid_amt': 'int',
        'ic1_bid_price': 'float',
        'ic1_bid_avail': 'int'
    }

    attribute_map = {
        'ticker': 'Ticker',
        'mm_buy': 'MMBuy',
        'mm_sell': 'MMSell',
        'ci1_average': 'CI1-Average',
        'ci1_ask_amt': 'CI1-AskAmt',
        'ci1_ask_price': 'CI1-AskPrice',
        'ci1_ask_avail': 'CI1-AskAvail',
        'ci1_bid_amt': 'CI1-BidAmt',
        'ci1_bid_price': 'CI1-BidPrice',
        'ci1_bid_avail': 'CI1-BidAvail',
        'ni1_average': 'NI1-Average',
        'ni1_ask_amt': 'NI1-AskAmt',
        'ni1_ask_price': 'NI1-AskPrice',
        'ni1_ask_avail': 'NI1-AskAvail',
        'ni1_bid_amt': 'NI1-BidAmt',
        'ni1_bid_price': 'NI1-BidPrice',
        'ni1_bid_avail': 'NI1-BidAvail',
        'ic1_average': 'IC1-Average',
        'ic1_ask_amt': 'IC1-AskAmt',
        'ic1_ask_price': 'IC1-AskPrice',
        'ic1_ask_avail': 'IC1-AskAvail',
        'ic1_bid_amt': 'IC1-BidAmt',
        'ic1_bid_price': 'IC1-BidPrice',
        'ic1_bid_avail': 'IC1-BidAvail'
    }

    def __init__(self, ticker=None, mm_buy=None, mm_sell=None, ci1_average=None, ci1_ask_amt=None, ci1_ask_price=None, ci1_ask_avail=None, ci1_bid_amt=None, ci1_bid_price=None, ci1_bid_avail=None, ni1_average=None, ni1_ask_amt=None, ni1_ask_price=None, ni1_ask_avail=None, ni1_bid_amt=None, ni1_bid_price=None, ni1_bid_avail=None, ic1_average=None, ic1_ask_amt=None, ic1_ask_price=None, ic1_ask_avail=None, ic1_bid_amt=None, ic1_bid_price=None, ic1_bid_avail=None):  # noqa: E501
        """RainPrices - a model defined in Swagger"""  # noqa: E501
        self._ticker = None
        self._mm_buy = None
        self._mm_sell = None
        self._ci1_average = None
        self._ci1_ask_amt = None
        self._ci1_ask_price = None
        self._ci1_ask_avail = None
        self._ci1_bid_amt = None
        self._ci1_bid_price = None
        self._ci1_bid_avail = None
        self._ni1_average = None
        self._ni1_ask_amt = None
        self._ni1_ask_price = None
        self._ni1_ask_avail = None
        self._ni1_bid_amt = None
        self._ni1_bid_price = None
        self._ni1_bid_avail = None
        self._ic1_average = None
        self._ic1_ask_amt = None
        self._ic1_ask_price = None
        self._ic1_ask_avail = None
        self._ic1_bid_amt = None
        self._ic1_bid_price = None
        self._ic1_bid_avail = None
        self.discriminator = None
        if ticker is not None:
            self.ticker = ticker
        if mm_buy is not None:
            self.mm_buy = mm_buy
        if mm_sell is not None:
            self.mm_sell = mm_sell
        if ci1_average is not None:
            self.ci1_average = ci1_average
        if ci1_ask_amt is not None:
            self.ci1_ask_amt = ci1_ask_amt
        if ci1_ask_price is not None:
            self.ci1_ask_price = ci1_ask_price
        if ci1_ask_avail is not None:
            self.ci1_ask_avail = ci1_ask_avail
        if ci1_bid_amt is not None:
            self.ci1_bid_amt = ci1_bid_amt
        if ci1_bid_price is not None:
            self.ci1_bid_price = ci1_bid_price
        if ci1_bid_avail is not None:
            self.ci1_bid_avail = ci1_bid_avail
        if ni1_average is not None:
            self.ni1_average = ni1_average
        if ni1_ask_amt is not None:
            self.ni1_ask_amt = ni1_ask_amt
        if ni1_ask_price is not None:
            self.ni1_ask_price = ni1_ask_price
        if ni1_ask_avail is not None:
            self.ni1_ask_avail = ni1_ask_avail
        if ni1_bid_amt is not None:
            self.ni1_bid_amt = ni1_bid_amt
        if ni1_bid_price is not None:
            self.ni1_bid_price = ni1_bid_price
        if ni1_bid_avail is not None:
            self.ni1_bid_avail = ni1_bid_avail
        if ic1_average is not None:
            self.ic1_average = ic1_average
        if ic1_ask_amt is not None:
            self.ic1_ask_amt = ic1_ask_amt
        if ic1_ask_price is not None:
            self.ic1_ask_price = ic1_ask_price
        if ic1_ask_avail is not None:
            self.ic1_ask_avail = ic1_ask_avail
        if ic1_bid_amt is not None:
            self.ic1_bid_amt = ic1_bid_amt
        if ic1_bid_price is not None:
            self.ic1_bid_price = ic1_bid_price
        if ic1_bid_avail is not None:
            self.ic1_bid_avail = ic1_bid_avail

    @property
    def ticker(self):
        """Gets the ticker of this RainPrices.  # noqa: E501

        The Ticker  # noqa: E501

        :return: The ticker of this RainPrices.  # noqa: E501
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker):
        """Sets the ticker of this RainPrices.

        The Ticker  # noqa: E501

        :param ticker: The ticker of this RainPrices.  # noqa: E501
        :type: str
        """

        self._ticker = ticker

    @property
    def mm_buy(self):
        """Gets the mm_buy of this RainPrices.  # noqa: E501

        The Market Maker buy (if present)  # noqa: E501

        :return: The mm_buy of this RainPrices.  # noqa: E501
        :rtype: float
        """
        return self._mm_buy

    @mm_buy.setter
    def mm_buy(self, mm_buy):
        """Sets the mm_buy of this RainPrices.

        The Market Maker buy (if present)  # noqa: E501

        :param mm_buy: The mm_buy of this RainPrices.  # noqa: E501
        :type: float
        """

        self._mm_buy = mm_buy

    @property
    def mm_sell(self):
        """Gets the mm_sell of this RainPrices.  # noqa: E501

        The Market Maker sell (if present)  # noqa: E501

        :return: The mm_sell of this RainPrices.  # noqa: E501
        :rtype: float
        """
        return self._mm_sell

    @mm_sell.setter
    def mm_sell(self, mm_sell):
        """Sets the mm_sell of this RainPrices.

        The Market Maker sell (if present)  # noqa: E501

        :param mm_sell: The mm_sell of this RainPrices.  # noqa: E501
        :type: float
        """

        self._mm_sell = mm_sell

    @property
    def ci1_average(self):
        """Gets the ci1_average of this RainPrices.  # noqa: E501

        The price average of the material on the CI1 exchange  # noqa: E501

        :return: The ci1_average of this RainPrices.  # noqa: E501
        :rtype: float
        """
        return self._ci1_average

    @ci1_average.setter
    def ci1_average(self, ci1_average):
        """Sets the ci1_average of this RainPrices.

        The price average of the material on the CI1 exchange  # noqa: E501

        :param ci1_average: The ci1_average of this RainPrices.  # noqa: E501
        :type: float
        """

        self._ci1_average = ci1_average

    @property
    def ci1_ask_amt(self):
        """Gets the ci1_ask_amt of this RainPrices.  # noqa: E501

        The amount of items available for the lowest asking price  # noqa: E501

        :return: The ci1_ask_amt of this RainPrices.  # noqa: E501
        :rtype: int
        """
        return self._ci1_ask_amt

    @ci1_ask_amt.setter
    def ci1_ask_amt(self, ci1_ask_amt):
        """Sets the ci1_ask_amt of this RainPrices.

        The amount of items available for the lowest asking price  # noqa: E501

        :param ci1_ask_amt: The ci1_ask_amt of this RainPrices.  # noqa: E501
        :type: int
        """

        self._ci1_ask_amt = ci1_ask_amt

    @property
    def ci1_ask_price(self):
        """Gets the ci1_ask_price of this RainPrices.  # noqa: E501

        The lowest asking price  # noqa: E501

        :return: The ci1_ask_price of this RainPrices.  # noqa: E501
        :rtype: float
        """
        return self._ci1_ask_price

    @ci1_ask_price.setter
    def ci1_ask_price(self, ci1_ask_price):
        """Sets the ci1_ask_price of this RainPrices.

        The lowest asking price  # noqa: E501

        :param ci1_ask_price: The ci1_ask_price of this RainPrices.  # noqa: E501
        :type: float
        """

        self._ci1_ask_price = ci1_ask_price

    @property
    def ci1_ask_avail(self):
        """Gets the ci1_ask_avail of this RainPrices.  # noqa: E501

        The amount of items listed available for buy across all ads  # noqa: E501

        :return: The ci1_ask_avail of this RainPrices.  # noqa: E501
        :rtype: int
        """
        return self._ci1_ask_avail

    @ci1_ask_avail.setter
    def ci1_ask_avail(self, ci1_ask_avail):
        """Sets the ci1_ask_avail of this RainPrices.

        The amount of items listed available for buy across all ads  # noqa: E501

        :param ci1_ask_avail: The ci1_ask_avail of this RainPrices.  # noqa: E501
        :type: int
        """

        self._ci1_ask_avail = ci1_ask_avail

    @property
    def ci1_bid_amt(self):
        """Gets the ci1_bid_amt of this RainPrices.  # noqa: E501

        The amount of items requested for the highest bid price  # noqa: E501

        :return: The ci1_bid_amt of this RainPrices.  # noqa: E501
        :rtype: int
        """
        return self._ci1_bid_amt

    @ci1_bid_amt.setter
    def ci1_bid_amt(self, ci1_bid_amt):
        """Sets the ci1_bid_amt of this RainPrices.

        The amount of items requested for the highest bid price  # noqa: E501

        :param ci1_bid_amt: The ci1_bid_amt of this RainPrices.  # noqa: E501
        :type: int
        """

        self._ci1_bid_amt = ci1_bid_amt

    @property
    def ci1_bid_price(self):
        """Gets the ci1_bid_price of this RainPrices.  # noqa: E501

        The highest bid price  # noqa: E501

        :return: The ci1_bid_price of this RainPrices.  # noqa: E501
        :rtype: float
        """
        return self._ci1_bid_price

    @ci1_bid_price.setter
    def ci1_bid_price(self, ci1_bid_price):
        """Sets the ci1_bid_price of this RainPrices.

        The highest bid price  # noqa: E501

        :param ci1_bid_price: The ci1_bid_price of this RainPrices.  # noqa: E501
        :type: float
        """

        self._ci1_bid_price = ci1_bid_price

    @property
    def ci1_bid_avail(self):
        """Gets the ci1_bid_avail of this RainPrices.  # noqa: E501

        The amount of items requesting to buy across all ads  # noqa: E501

        :return: The ci1_bid_avail of this RainPrices.  # noqa: E501
        :rtype: int
        """
        return self._ci1_bid_avail

    @ci1_bid_avail.setter
    def ci1_bid_avail(self, ci1_bid_avail):
        """Sets the ci1_bid_avail of this RainPrices.

        The amount of items requesting to buy across all ads  # noqa: E501

        :param ci1_bid_avail: The ci1_bid_avail of this RainPrices.  # noqa: E501
        :type: int
        """

        self._ci1_bid_avail = ci1_bid_avail

    @property
    def ni1_average(self):
        """Gets the ni1_average of this RainPrices.  # noqa: E501

        The price average of the material on the NC1 exchange  # noqa: E501

        :return: The ni1_average of this RainPrices.  # noqa: E501
        :rtype: float
        """
        return self._ni1_average

    @ni1_average.setter
    def ni1_average(self, ni1_average):
        """Sets the ni1_average of this RainPrices.

        The price average of the material on the NC1 exchange  # noqa: E501

        :param ni1_average: The ni1_average of this RainPrices.  # noqa: E501
        :type: float
        """

        self._ni1_average = ni1_average

    @property
    def ni1_ask_amt(self):
        """Gets the ni1_ask_amt of this RainPrices.  # noqa: E501

        The amount of items available for the lowest asking price  # noqa: E501

        :return: The ni1_ask_amt of this RainPrices.  # noqa: E501
        :rtype: int
        """
        return self._ni1_ask_amt

    @ni1_ask_amt.setter
    def ni1_ask_amt(self, ni1_ask_amt):
        """Sets the ni1_ask_amt of this RainPrices.

        The amount of items available for the lowest asking price  # noqa: E501

        :param ni1_ask_amt: The ni1_ask_amt of this RainPrices.  # noqa: E501
        :type: int
        """

        self._ni1_ask_amt = ni1_ask_amt

    @property
    def ni1_ask_price(self):
        """Gets the ni1_ask_price of this RainPrices.  # noqa: E501

        The lowest asking price  # noqa: E501

        :return: The ni1_ask_price of this RainPrices.  # noqa: E501
        :rtype: float
        """
        return self._ni1_ask_price

    @ni1_ask_price.setter
    def ni1_ask_price(self, ni1_ask_price):
        """Sets the ni1_ask_price of this RainPrices.

        The lowest asking price  # noqa: E501

        :param ni1_ask_price: The ni1_ask_price of this RainPrices.  # noqa: E501
        :type: float
        """

        self._ni1_ask_price = ni1_ask_price

    @property
    def ni1_ask_avail(self):
        """Gets the ni1_ask_avail of this RainPrices.  # noqa: E501

        The amount of items listed available for buy across all ads  # noqa: E501

        :return: The ni1_ask_avail of this RainPrices.  # noqa: E501
        :rtype: int
        """
        return self._ni1_ask_avail

    @ni1_ask_avail.setter
    def ni1_ask_avail(self, ni1_ask_avail):
        """Sets the ni1_ask_avail of this RainPrices.

        The amount of items listed available for buy across all ads  # noqa: E501

        :param ni1_ask_avail: The ni1_ask_avail of this RainPrices.  # noqa: E501
        :type: int
        """

        self._ni1_ask_avail = ni1_ask_avail

    @property
    def ni1_bid_amt(self):
        """Gets the ni1_bid_amt of this RainPrices.  # noqa: E501

        The amount of items requested for the highest bid price  # noqa: E501

        :return: The ni1_bid_amt of this RainPrices.  # noqa: E501
        :rtype: int
        """
        return self._ni1_bid_amt

    @ni1_bid_amt.setter
    def ni1_bid_amt(self, ni1_bid_amt):
        """Sets the ni1_bid_amt of this RainPrices.

        The amount of items requested for the highest bid price  # noqa: E501

        :param ni1_bid_amt: The ni1_bid_amt of this RainPrices.  # noqa: E501
        :type: int
        """

        self._ni1_bid_amt = ni1_bid_amt

    @property
    def ni1_bid_price(self):
        """Gets the ni1_bid_price of this RainPrices.  # noqa: E501

        The highest bid price  # noqa: E501

        :return: The ni1_bid_price of this RainPrices.  # noqa: E501
        :rtype: float
        """
        return self._ni1_bid_price

    @ni1_bid_price.setter
    def ni1_bid_price(self, ni1_bid_price):
        """Sets the ni1_bid_price of this RainPrices.

        The highest bid price  # noqa: E501

        :param ni1_bid_price: The ni1_bid_price of this RainPrices.  # noqa: E501
        :type: float
        """

        self._ni1_bid_price = ni1_bid_price

    @property
    def ni1_bid_avail(self):
        """Gets the ni1_bid_avail of this RainPrices.  # noqa: E501

        The amount of items requesting to buy across all ads  # noqa: E501

        :return: The ni1_bid_avail of this RainPrices.  # noqa: E501
        :rtype: int
        """
        return self._ni1_bid_avail

    @ni1_bid_avail.setter
    def ni1_bid_avail(self, ni1_bid_avail):
        """Sets the ni1_bid_avail of this RainPrices.

        The amount of items requesting to buy across all ads  # noqa: E501

        :param ni1_bid_avail: The ni1_bid_avail of this RainPrices.  # noqa: E501
        :type: int
        """

        self._ni1_bid_avail = ni1_bid_avail

    @property
    def ic1_average(self):
        """Gets the ic1_average of this RainPrices.  # noqa: E501

        The price average of the material on the IC1 exchange  # noqa: E501

        :return: The ic1_average of this RainPrices.  # noqa: E501
        :rtype: float
        """
        return self._ic1_average

    @ic1_average.setter
    def ic1_average(self, ic1_average):
        """Sets the ic1_average of this RainPrices.

        The price average of the material on the IC1 exchange  # noqa: E501

        :param ic1_average: The ic1_average of this RainPrices.  # noqa: E501
        :type: float
        """

        self._ic1_average = ic1_average

    @property
    def ic1_ask_amt(self):
        """Gets the ic1_ask_amt of this RainPrices.  # noqa: E501

        The amount of items available for the lowest asking price  # noqa: E501

        :return: The ic1_ask_amt of this RainPrices.  # noqa: E501
        :rtype: int
        """
        return self._ic1_ask_amt

    @ic1_ask_amt.setter
    def ic1_ask_amt(self, ic1_ask_amt):
        """Sets the ic1_ask_amt of this RainPrices.

        The amount of items available for the lowest asking price  # noqa: E501

        :param ic1_ask_amt: The ic1_ask_amt of this RainPrices.  # noqa: E501
        :type: int
        """

        self._ic1_ask_amt = ic1_ask_amt

    @property
    def ic1_ask_price(self):
        """Gets the ic1_ask_price of this RainPrices.  # noqa: E501

        The lowest asking price  # noqa: E501

        :return: The ic1_ask_price of this RainPrices.  # noqa: E501
        :rtype: float
        """
        return self._ic1_ask_price

    @ic1_ask_price.setter
    def ic1_ask_price(self, ic1_ask_price):
        """Sets the ic1_ask_price of this RainPrices.

        The lowest asking price  # noqa: E501

        :param ic1_ask_price: The ic1_ask_price of this RainPrices.  # noqa: E501
        :type: float
        """

        self._ic1_ask_price = ic1_ask_price

    @property
    def ic1_ask_avail(self):
        """Gets the ic1_ask_avail of this RainPrices.  # noqa: E501

        The amount of items listed available for buy across all ads  # noqa: E501

        :return: The ic1_ask_avail of this RainPrices.  # noqa: E501
        :rtype: int
        """
        return self._ic1_ask_avail

    @ic1_ask_avail.setter
    def ic1_ask_avail(self, ic1_ask_avail):
        """Sets the ic1_ask_avail of this RainPrices.

        The amount of items listed available for buy across all ads  # noqa: E501

        :param ic1_ask_avail: The ic1_ask_avail of this RainPrices.  # noqa: E501
        :type: int
        """

        self._ic1_ask_avail = ic1_ask_avail

    @property
    def ic1_bid_amt(self):
        """Gets the ic1_bid_amt of this RainPrices.  # noqa: E501

        The amount of items requested for the highest bid price  # noqa: E501

        :return: The ic1_bid_amt of this RainPrices.  # noqa: E501
        :rtype: int
        """
        return self._ic1_bid_amt

    @ic1_bid_amt.setter
    def ic1_bid_amt(self, ic1_bid_amt):
        """Sets the ic1_bid_amt of this RainPrices.

        The amount of items requested for the highest bid price  # noqa: E501

        :param ic1_bid_amt: The ic1_bid_amt of this RainPrices.  # noqa: E501
        :type: int
        """

        self._ic1_bid_amt = ic1_bid_amt

    @property
    def ic1_bid_price(self):
        """Gets the ic1_bid_price of this RainPrices.  # noqa: E501

        The highest bid price  # noqa: E501

        :return: The ic1_bid_price of this RainPrices.  # noqa: E501
        :rtype: float
        """
        return self._ic1_bid_price

    @ic1_bid_price.setter
    def ic1_bid_price(self, ic1_bid_price):
        """Sets the ic1_bid_price of this RainPrices.

        The highest bid price  # noqa: E501

        :param ic1_bid_price: The ic1_bid_price of this RainPrices.  # noqa: E501
        :type: float
        """

        self._ic1_bid_price = ic1_bid_price

    @property
    def ic1_bid_avail(self):
        """Gets the ic1_bid_avail of this RainPrices.  # noqa: E501

        The amount of items requesting to buy across all ads  # noqa: E501

        :return: The ic1_bid_avail of this RainPrices.  # noqa: E501
        :rtype: int
        """
        return self._ic1_bid_avail

    @ic1_bid_avail.setter
    def ic1_bid_avail(self, ic1_bid_avail):
        """Sets the ic1_bid_avail of this RainPrices.

        The amount of items requesting to buy across all ads  # noqa: E501

        :param ic1_bid_avail: The ic1_bid_avail of this RainPrices.  # noqa: E501
        :type: int
        """

        self._ic1_bid_avail = ic1_bid_avail

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RainPrices, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RainPrices):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
