# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RainPlanetProductionOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_id': 'str',
        'material': 'str',
        'count': 'int'
    }

    attribute_map = {
        'order_id': 'OrderId',
        'material': 'Material',
        'count': 'Count'
    }

    def __init__(self, order_id=None, material=None, count=None):  # noqa: E501
        """RainPlanetProductionOutput - a model defined in Swagger"""  # noqa: E501
        self._order_id = None
        self._material = None
        self._count = None
        self.discriminator = None
        if order_id is not None:
            self.order_id = order_id
        if material is not None:
            self.material = material
        if count is not None:
            self.count = count

    @property
    def order_id(self):
        """Gets the order_id of this RainPlanetProductionOutput.  # noqa: E501

        The right-hand side hash is the first 8 characters of the Production id  # noqa: E501

        :return: The order_id of this RainPlanetProductionOutput.  # noqa: E501
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this RainPlanetProductionOutput.

        The right-hand side hash is the first 8 characters of the Production id  # noqa: E501

        :param order_id: The order_id of this RainPlanetProductionOutput.  # noqa: E501
        :type: str
        """

        self._order_id = order_id

    @property
    def material(self):
        """Gets the material of this RainPlanetProductionOutput.  # noqa: E501


        :return: The material of this RainPlanetProductionOutput.  # noqa: E501
        :rtype: str
        """
        return self._material

    @material.setter
    def material(self, material):
        """Sets the material of this RainPlanetProductionOutput.


        :param material: The material of this RainPlanetProductionOutput.  # noqa: E501
        :type: str
        """

        self._material = material

    @property
    def count(self):
        """Gets the count of this RainPlanetProductionOutput.  # noqa: E501


        :return: The count of this RainPlanetProductionOutput.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this RainPlanetProductionOutput.


        :param count: The count of this RainPlanetProductionOutput.  # noqa: E501
        :type: int
        """

        self._count = count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RainPlanetProductionOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RainPlanetProductionOutput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
