# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RecipeMinimalRecipe(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'building_ticker': 'str',
        'recipe_name': 'str',
        'inputs': 'list[RecipeMinimalInput]',
        'outputs': 'list[RecipeMinimalOutput]',
        'time_ms': 'int'
    }

    attribute_map = {
        'building_ticker': 'BuildingTicker',
        'recipe_name': 'RecipeName',
        'inputs': 'Inputs',
        'outputs': 'Outputs',
        'time_ms': 'TimeMs'
    }

    def __init__(self, building_ticker=None, recipe_name=None, inputs=None, outputs=None, time_ms=None):  # noqa: E501
        """RecipeMinimalRecipe - a model defined in Swagger"""  # noqa: E501
        self._building_ticker = None
        self._recipe_name = None
        self._inputs = None
        self._outputs = None
        self._time_ms = None
        self.discriminator = None
        if building_ticker is not None:
            self.building_ticker = building_ticker
        if recipe_name is not None:
            self.recipe_name = recipe_name
        if inputs is not None:
            self.inputs = inputs
        if outputs is not None:
            self.outputs = outputs
        if time_ms is not None:
            self.time_ms = time_ms

    @property
    def building_ticker(self):
        """Gets the building_ticker of this RecipeMinimalRecipe.  # noqa: E501


        :return: The building_ticker of this RecipeMinimalRecipe.  # noqa: E501
        :rtype: str
        """
        return self._building_ticker

    @building_ticker.setter
    def building_ticker(self, building_ticker):
        """Sets the building_ticker of this RecipeMinimalRecipe.


        :param building_ticker: The building_ticker of this RecipeMinimalRecipe.  # noqa: E501
        :type: str
        """

        self._building_ticker = building_ticker

    @property
    def recipe_name(self):
        """Gets the recipe_name of this RecipeMinimalRecipe.  # noqa: E501


        :return: The recipe_name of this RecipeMinimalRecipe.  # noqa: E501
        :rtype: str
        """
        return self._recipe_name

    @recipe_name.setter
    def recipe_name(self, recipe_name):
        """Sets the recipe_name of this RecipeMinimalRecipe.


        :param recipe_name: The recipe_name of this RecipeMinimalRecipe.  # noqa: E501
        :type: str
        """

        self._recipe_name = recipe_name

    @property
    def inputs(self):
        """Gets the inputs of this RecipeMinimalRecipe.  # noqa: E501


        :return: The inputs of this RecipeMinimalRecipe.  # noqa: E501
        :rtype: list[RecipeMinimalInput]
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs):
        """Sets the inputs of this RecipeMinimalRecipe.


        :param inputs: The inputs of this RecipeMinimalRecipe.  # noqa: E501
        :type: list[RecipeMinimalInput]
        """

        self._inputs = inputs

    @property
    def outputs(self):
        """Gets the outputs of this RecipeMinimalRecipe.  # noqa: E501


        :return: The outputs of this RecipeMinimalRecipe.  # noqa: E501
        :rtype: list[RecipeMinimalOutput]
        """
        return self._outputs

    @outputs.setter
    def outputs(self, outputs):
        """Sets the outputs of this RecipeMinimalRecipe.


        :param outputs: The outputs of this RecipeMinimalRecipe.  # noqa: E501
        :type: list[RecipeMinimalOutput]
        """

        self._outputs = outputs

    @property
    def time_ms(self):
        """Gets the time_ms of this RecipeMinimalRecipe.  # noqa: E501

        Time in milliseconds  # noqa: E501

        :return: The time_ms of this RecipeMinimalRecipe.  # noqa: E501
        :rtype: int
        """
        return self._time_ms

    @time_ms.setter
    def time_ms(self, time_ms):
        """Sets the time_ms of this RecipeMinimalRecipe.

        Time in milliseconds  # noqa: E501

        :param time_ms: The time_ms of this RecipeMinimalRecipe.  # noqa: E501
        :type: int
        """

        self._time_ms = time_ms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RecipeMinimalRecipe, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecipeMinimalRecipe):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
