# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserSettingsBurnRateExclusion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'planet_natural_id': 'str',
        'material_ticker': 'str'
    }

    attribute_map = {
        'planet_natural_id': 'PlanetNaturalId',
        'material_ticker': 'MaterialTicker'
    }

    def __init__(self, planet_natural_id=None, material_ticker=None):  # noqa: E501
        """UserSettingsBurnRateExclusion - a model defined in Swagger"""  # noqa: E501
        self._planet_natural_id = None
        self._material_ticker = None
        self.discriminator = None
        if planet_natural_id is not None:
            self.planet_natural_id = planet_natural_id
        if material_ticker is not None:
            self.material_ticker = material_ticker

    @property
    def planet_natural_id(self):
        """Gets the planet_natural_id of this UserSettingsBurnRateExclusion.  # noqa: E501


        :return: The planet_natural_id of this UserSettingsBurnRateExclusion.  # noqa: E501
        :rtype: str
        """
        return self._planet_natural_id

    @planet_natural_id.setter
    def planet_natural_id(self, planet_natural_id):
        """Sets the planet_natural_id of this UserSettingsBurnRateExclusion.


        :param planet_natural_id: The planet_natural_id of this UserSettingsBurnRateExclusion.  # noqa: E501
        :type: str
        """

        self._planet_natural_id = planet_natural_id

    @property
    def material_ticker(self):
        """Gets the material_ticker of this UserSettingsBurnRateExclusion.  # noqa: E501


        :return: The material_ticker of this UserSettingsBurnRateExclusion.  # noqa: E501
        :rtype: str
        """
        return self._material_ticker

    @material_ticker.setter
    def material_ticker(self, material_ticker):
        """Sets the material_ticker of this UserSettingsBurnRateExclusion.


        :param material_ticker: The material_ticker of this UserSettingsBurnRateExclusion.  # noqa: E501
        :type: str
        """

        self._material_ticker = material_ticker

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserSettingsBurnRateExclusion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserSettingsBurnRateExclusion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
