# coding: utf-8

"""
    FIO API

    FIO REST API.  Instructions for testing the API:  1) Click on /auth/login endpoint  2) Click the `Try it out` button  3) Enter your credentials into the JSON payload  4) Copy the resultant value for `AuthToken` (the GUID inside the quotes)  5) Click on `Authorize` and paste in the AuthToken  6) Commands with the lock icon will now function, assuming appropriate parameters/settings are present   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from fio_sdk.api_client import ApiClient


class ExchangeApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def exchange_all_get(self, **kwargs):  # noqa: E501
        """Retrieves summarized information of all exchange data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_all_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.exchange_all_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.exchange_all_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def exchange_all_get_with_http_info(self, **kwargs):  # noqa: E501
        """Retrieves summarized information of all exchange data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_all_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method exchange_all_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/exchange/all', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def exchange_cxpc_exchange_ticker_get(self, exchange_ticker, **kwargs):  # noqa: E501
        """Retrieves exchange price chart data for the given ticker  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_cxpc_exchange_ticker_get(exchange_ticker, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str exchange_ticker: Format: 'Material.ExchangeCode' (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.exchange_cxpc_exchange_ticker_get_with_http_info(exchange_ticker, **kwargs)  # noqa: E501
        else:
            (data) = self.exchange_cxpc_exchange_ticker_get_with_http_info(exchange_ticker, **kwargs)  # noqa: E501
            return data

    def exchange_cxpc_exchange_ticker_get_with_http_info(self, exchange_ticker, **kwargs):  # noqa: E501
        """Retrieves exchange price chart data for the given ticker  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_cxpc_exchange_ticker_get_with_http_info(exchange_ticker, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str exchange_ticker: Format: 'Material.ExchangeCode' (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['exchange_ticker']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method exchange_cxpc_exchange_ticker_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'exchange_ticker' is set
        if ('exchange_ticker' not in params or
                params['exchange_ticker'] is None):
            raise ValueError("Missing the required parameter `exchange_ticker` when calling `exchange_cxpc_exchange_ticker_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'exchange_ticker' in params:
            path_params['ExchangeTicker'] = params['exchange_ticker']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/exchange/cxpc/{ExchangeTicker}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def exchange_cxpc_exchange_ticker_time_stamp_get(self, exchange_ticker, time_stamp, **kwargs):  # noqa: E501
        """Retrieves exchange price chart data for the given ticker  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_cxpc_exchange_ticker_time_stamp_get(exchange_ticker, time_stamp, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str exchange_ticker: Format: 'Material.ExchangeCode' (required)
        :param int time_stamp: Format: 'Milliseconds since epoch, UTC' (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.exchange_cxpc_exchange_ticker_time_stamp_get_with_http_info(exchange_ticker, time_stamp, **kwargs)  # noqa: E501
        else:
            (data) = self.exchange_cxpc_exchange_ticker_time_stamp_get_with_http_info(exchange_ticker, time_stamp, **kwargs)  # noqa: E501
            return data

    def exchange_cxpc_exchange_ticker_time_stamp_get_with_http_info(self, exchange_ticker, time_stamp, **kwargs):  # noqa: E501
        """Retrieves exchange price chart data for the given ticker  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_cxpc_exchange_ticker_time_stamp_get_with_http_info(exchange_ticker, time_stamp, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str exchange_ticker: Format: 'Material.ExchangeCode' (required)
        :param int time_stamp: Format: 'Milliseconds since epoch, UTC' (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['exchange_ticker', 'time_stamp']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method exchange_cxpc_exchange_ticker_time_stamp_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'exchange_ticker' is set
        if ('exchange_ticker' not in params or
                params['exchange_ticker'] is None):
            raise ValueError("Missing the required parameter `exchange_ticker` when calling `exchange_cxpc_exchange_ticker_time_stamp_get`")  # noqa: E501
        # verify the required parameter 'time_stamp' is set
        if ('time_stamp' not in params or
                params['time_stamp'] is None):
            raise ValueError("Missing the required parameter `time_stamp` when calling `exchange_cxpc_exchange_ticker_time_stamp_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'exchange_ticker' in params:
            path_params['ExchangeTicker'] = params['exchange_ticker']  # noqa: E501
        if 'time_stamp' in params:
            path_params['TimeStamp'] = params['time_stamp']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/exchange/cxpc/{ExchangeTicker}/{TimeStamp}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def exchange_exchange_ticker_get(self, exchange_ticker, **kwargs):  # noqa: E501
        """Retrieves Exchange data for the provided ExchangeTicker  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_exchange_ticker_get(exchange_ticker, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str exchange_ticker: Format: 'Material.ExchangeCode' (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.exchange_exchange_ticker_get_with_http_info(exchange_ticker, **kwargs)  # noqa: E501
        else:
            (data) = self.exchange_exchange_ticker_get_with_http_info(exchange_ticker, **kwargs)  # noqa: E501
            return data

    def exchange_exchange_ticker_get_with_http_info(self, exchange_ticker, **kwargs):  # noqa: E501
        """Retrieves Exchange data for the provided ExchangeTicker  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_exchange_ticker_get_with_http_info(exchange_ticker, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str exchange_ticker: Format: 'Material.ExchangeCode' (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['exchange_ticker']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method exchange_exchange_ticker_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'exchange_ticker' is set
        if ('exchange_ticker' not in params or
                params['exchange_ticker'] is None):
            raise ValueError("Missing the required parameter `exchange_ticker` when calling `exchange_exchange_ticker_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'exchange_ticker' in params:
            path_params['ExchangeTicker'] = params['exchange_ticker']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/exchange/{ExchangeTicker}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def exchange_full_get(self, **kwargs):  # noqa: E501
        """Retrieves all the exchange data, including order info  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_full_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.exchange_full_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.exchange_full_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def exchange_full_get_with_http_info(self, **kwargs):  # noqa: E501
        """Retrieves all the exchange data, including order info  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_full_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method exchange_full_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/exchange/full', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def exchange_orders_company_code_exchange_code_get(self, company_code, exchange_code, **kwargs):  # noqa: E501
        """Retrieves a provided company code's orders on all exchanges  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_orders_company_code_exchange_code_get(company_code, exchange_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str company_code: The 1 to 4 character company code (required)
        :param str exchange_code: The 3 character exchange code (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.exchange_orders_company_code_exchange_code_get_with_http_info(company_code, exchange_code, **kwargs)  # noqa: E501
        else:
            (data) = self.exchange_orders_company_code_exchange_code_get_with_http_info(company_code, exchange_code, **kwargs)  # noqa: E501
            return data

    def exchange_orders_company_code_exchange_code_get_with_http_info(self, company_code, exchange_code, **kwargs):  # noqa: E501
        """Retrieves a provided company code's orders on all exchanges  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_orders_company_code_exchange_code_get_with_http_info(company_code, exchange_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str company_code: The 1 to 4 character company code (required)
        :param str exchange_code: The 3 character exchange code (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['company_code', 'exchange_code']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method exchange_orders_company_code_exchange_code_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'company_code' is set
        if ('company_code' not in params or
                params['company_code'] is None):
            raise ValueError("Missing the required parameter `company_code` when calling `exchange_orders_company_code_exchange_code_get`")  # noqa: E501
        # verify the required parameter 'exchange_code' is set
        if ('exchange_code' not in params or
                params['exchange_code'] is None):
            raise ValueError("Missing the required parameter `exchange_code` when calling `exchange_orders_company_code_exchange_code_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'company_code' in params:
            path_params['CompanyCode'] = params['company_code']  # noqa: E501
        if 'exchange_code' in params:
            path_params['ExchangeCode'] = params['exchange_code']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/exchange/orders/{CompanyCode}/{ExchangeCode}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def exchange_orders_company_code_get(self, company_code, **kwargs):  # noqa: E501
        """Retrieves a provided company code's orders on all exchanges  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_orders_company_code_get(company_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str company_code: The 1 to 4 character company code (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.exchange_orders_company_code_get_with_http_info(company_code, **kwargs)  # noqa: E501
        else:
            (data) = self.exchange_orders_company_code_get_with_http_info(company_code, **kwargs)  # noqa: E501
            return data

    def exchange_orders_company_code_get_with_http_info(self, company_code, **kwargs):  # noqa: E501
        """Retrieves a provided company code's orders on all exchanges  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_orders_company_code_get_with_http_info(company_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str company_code: The 1 to 4 character company code (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['company_code']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method exchange_orders_company_code_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'company_code' is set
        if ('company_code' not in params or
                params['company_code'] is None):
            raise ValueError("Missing the required parameter `company_code` when calling `exchange_orders_company_code_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'company_code' in params:
            path_params['CompanyCode'] = params['company_code']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/exchange/orders/{CompanyCode}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def exchange_post(self, **kwargs):  # noqa: E501
        """Posts COMEX_BROKER_DATA data payload  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.exchange_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.exchange_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def exchange_post_with_http_info(self, **kwargs):  # noqa: E501
        """Posts COMEX_BROKER_DATA data payload  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method exchange_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/exchange', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def exchange_station_get(self, **kwargs):  # noqa: E501
        """Retrieves all exchange station data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_station_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.exchange_station_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.exchange_station_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def exchange_station_get_with_http_info(self, **kwargs):  # noqa: E501
        """Retrieves all exchange station data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.exchange_station_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method exchange_station_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/exchange/station', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
